import { ReactNode, useEffect } from "react";
import { FileDown, Printer, X } from "lucide-react";
import { Modal } from "../ui/Modal";
import { Button } from "../ui/Button";
import logo from "../../assets/college-logo.jpeg";
import { COLLEGE_NAME } from "../../constants";

/**
 * The official document view — used for both "Preview Report" and "Print Report".
 * Everything inside #report-print-area is what survives the print stylesheet (see
 * index.css's @media print block); the sidebar, navbar and these action buttons
 * themselves (marked .no-print) are stripped out of the printed page.
 */
export function ReportPreview({
  open,
  onClose,
  reportTitle,
  generatedBy,
  onDownload,
  downloading,
  autoPrint,
  children,
}: {
  open: boolean;
  onClose: () => void;
  reportTitle: string;
  generatedBy: string;
  onDownload: () => void;
  downloading: boolean;
  /** Set when opened via the "Print Report" action, so printing fires as soon as the preview is ready. */
  autoPrint?: boolean;
  children: ReactNode;
}) {
  useEffect(() => {
    if (open && autoPrint) {
      const timer = setTimeout(() => window.print(), 150);
      return () => clearTimeout(timer);
    }
  }, [open, autoPrint]);

  return (
    <Modal open={open} onClose={onClose} title="Report Preview" maxWidth="max-w-2xl">
      <div id="report-print-area">
        <div className="flex items-center gap-4 border-b border-gold-200 pb-4">
          <img src={logo} alt="" className="h-14 w-14 shrink-0 rounded-full object-cover" />
          <div>
            <p className="font-serif text-lg font-bold text-brand-950">{COLLEGE_NAME}</p>
            <p className="text-xs uppercase tracking-wide text-slate-500">Smart College Management System</p>
          </div>
        </div>
        <h3 className="mt-4 text-center font-serif text-base font-bold uppercase tracking-wide text-brand-900">
          {reportTitle}
        </h3>

        <div className="mt-5">{children}</div>

        <div className="mt-6 border-t border-slate-100 pt-3 text-xs text-slate-400">
          <p>Generated on {new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</p>
          <p>Generated by {generatedBy}</p>
        </div>

        <div className="no-print mt-6 flex flex-wrap justify-end gap-2">
          <Button variant="outline" size="sm" onClick={onClose}>
            <X className="h-3.5 w-3.5" /> Close
          </Button>
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Printer className="h-3.5 w-3.5" /> Print
          </Button>
          <Button size="sm" onClick={onDownload} loading={downloading}>
            <FileDown className="h-3.5 w-3.5" /> Download PDF
          </Button>
        </div>
      </div>
    </Modal>
  );
}
