// Type-only import — the real jsPDF/autoTable modules are loaded lazily inside each
// generate*Pdf() function below, so these heavy libraries never bloat the main bundle
// for users who never open Reports.
import type { jsPDF as JsPDF } from "jspdf";
import logoUrl from "../assets/college-logo.jpeg";
import { COLLEGE_NAME } from "../constants";
import {
  StudentDetailsReportData,
  StudentMarksReportData,
  FacultyDetailsReportData,
  MarksColumns,
  FeedbackClassReportRow,
  FeedbackFacultyDetail,
} from "../types";
import { shortAcademicYear } from "./format";

const NAVY = "#071a33";
const GOLD = "#b8944a";
const SLATE = "#526274";
const MARGIN = 40;

let logoDataUrlPromise: Promise<string | null> | null = null;

/** Fetches the real college logo once and caches it as a data URL for embedding in PDFs. */
function loadLogoDataUrl(): Promise<string | null> {
  if (!logoDataUrlPromise) {
    logoDataUrlPromise = fetch(logoUrl)
      .then((res) => res.blob())
      .then(
        (blob) =>
          new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
          })
      )
      .catch(() => null);
  }
  return logoDataUrlPromise;
}

function formatDateTime(date: Date) {
  return date.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

async function addHeader(pdf: JsPDF, title: string, titleBadge?: string) {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const logo = await loadLogoDataUrl();

  if (logo) {
    try {
      pdf.addImage(logo, "JPEG", MARGIN, MARGIN, 44, 44);
    } catch {
      // A logo that fails to decode shouldn't block the whole report from generating.
    }
  }

  const textX = MARGIN + (logo ? 56 : 0);
  pdf.setTextColor(NAVY);
  pdf.setFont("times", "bold");
  pdf.setFontSize(16);
  pdf.text(COLLEGE_NAME.toUpperCase(), textX, MARGIN + 16);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(SLATE);
  pdf.text("SMART COLLEGE MANAGEMENT SYSTEM", textX, MARGIN + 30);

  pdf.setDrawColor(GOLD);
  pdf.setLineWidth(1.2);
  pdf.line(MARGIN, MARGIN + 54, pageWidth - MARGIN, MARGIN + 54);

  pdf.setFont("times", "bold");
  pdf.setFontSize(13);
  pdf.setTextColor(NAVY);
  pdf.text(title.toUpperCase(), pageWidth / 2, MARGIN + 76, { align: "center" });

  if (titleBadge) {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(SLATE);
    pdf.text(`A.Y. ${titleBadge}`, pageWidth - MARGIN, MARGIN + 76, { align: "right" });
  }

  return MARGIN + 96;
}

function addFooter(pdf: JsPDF, generatedBy: string) {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const pageCount = pdf.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setDrawColor(220, 220, 220);
    pdf.setLineWidth(0.5);
    pdf.line(MARGIN, pageHeight - 46, pageWidth - MARGIN, pageHeight - 46);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(SLATE);
    pdf.text(`Generated on ${formatDateTime(new Date())} · Generated by ${generatedBy}`, MARGIN, pageHeight - 32);
    pdf.text(`Page ${i} of ${pageCount}`, pageWidth - MARGIN, pageHeight - 32, { align: "right" });
    pdf.text("This is a system-generated report from the Smart College Management System.", pageWidth / 2, pageHeight - 20, {
      align: "center",
    });
  }
}

function fieldRows(pdf: JsPDF, startY: number, rows: [string, string][]) {
  let y = startY;
  const labelX = MARGIN;
  const valueX = MARGIN + 150;

  rows.forEach(([label, value]) => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(SLATE);
    pdf.text(label, labelX, y);

    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(NAVY);
    pdf.text(value || "—", valueX, y);
    y += 20;
  });

  return y;
}

export async function generateStudentDetailsPdf(data: StudentDetailsReportData, generatedBy: string) {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const startY = await addHeader(pdf, "Student Details Report");

  fieldRows(pdf, startY + 10, [
    ["Student ID", data.studentId],
    ["Student Name", data.fullName],
    ["Department", `${data.department} (${data.departmentCode})`],
    ["Year", `Year ${data.year}${data.semester ? ` · Semester ${data.semester}` : ""}`],
    ["Section", data.section],
    ["Email", data.email],
    ["Phone", data.phone],
    ["Account Status", data.accountActive ? "Active" : "Inactive"],
  ]);

  addFooter(pdf, generatedBy);
  pdf.save(`Student_Details_${data.studentId}.pdf`);
}

export async function generateStudentMarksPdf(
  data: StudentMarksReportData,
  generatedBy: string,
  columns: MarksColumns = { mid1: true, mid2: true, semester: true }
) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const academicYear = data.subjects[0] ? shortAcademicYear(data.subjects[0].academicYear) : undefined;
  const startY = await addHeader(pdf, "Student Marks Report", academicYear);

  let y = fieldRows(pdf, startY + 10, [
    ["Student Name", data.fullName],
    ["Roll Number", data.studentId],
    ["Department", `${data.department} (${data.departmentCode})`],
    ["Year", `Year ${data.year}${data.semester ? ` · Semester ${data.semester}` : ""}`],
    ["Section", data.section],
  ]);
  y += 10;

  if (data.subjects.length === 0) {
    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(10);
    pdf.setTextColor(SLATE);
    pdf.text("No marks have been recorded for this student yet.", MARGIN, y + 20);
  } else {
    autoTable(pdf, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [
        [
          "Subject",
          ...(columns.mid1 ? ["Mid 1"] : []),
          ...(columns.mid2 ? ["Mid 2"] : []),
          ...(columns.semester ? ["Semester"] : []),
        ],
      ],
      body: data.subjects.map((s) => [
        s.subject,
        ...(columns.mid1 ? [s.mid1 ?? "—"] : []),
        ...(columns.mid2 ? [s.mid2 ?? "—"] : []),
        ...(columns.semester ? [s.semester ?? "—"] : []),
      ]),
      headStyles: { fillColor: [7, 26, 51], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, textColor: [7, 26, 51] },
      alternateRowStyles: { fillColor: [248, 246, 240] },
    });
  }

  addFooter(pdf, generatedBy);
  pdf.save(`Student_Marks_${data.studentId}.pdf`);
}

export async function generateFacultyDetailsPdf(data: FacultyDetailsReportData, generatedBy: string) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const startY = await addHeader(pdf, "Faculty Details Report");

  const name = data.title ? `${data.title} ${data.fullName}` : data.fullName;
  let y = fieldRows(pdf, startY + 10, [
    ["Faculty ID", data.facultyId],
    ["Faculty Name", name],
    ["Department", `${data.department} (${data.departmentCode})`],
    ["Designation", data.designation],
    ["Email", data.email],
    ["Phone", data.phone],
    ["Status", data.status === "ACTIVE" ? "Active" : "Inactive"],
    ["Added to System", new Date(data.addedToSystemAt).toLocaleDateString("en-IN", { dateStyle: "medium" })],
  ]);
  y += 6;

  if (data.assignedSubjects.length || data.assignedSections.length) {
    fieldRows(pdf, y + 14, [
      ["Assigned Subjects", data.assignedSubjects.join(", ") || "—"],
      ["Assigned Sections", data.assignedSections.join(", ") || "—"],
      ["Assigned Rooms", data.assignedRooms.join(", ") || "—"],
      ["Assigned Blocks", data.assignedBlocks.join(", ") || "—"],
    ]);
    y += 14 + 20 * 4 + 10;
  }

  if (data.timetable.length > 0) {
    autoTable(pdf, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Day", "Time", "Subject", "Section", "Room", "Block"]],
      body: data.timetable.map((t) => [
        t.day,
        `${t.startTime} – ${t.endTime}`,
        t.subject,
        `Year ${t.year} - ${t.section}`,
        t.room,
        t.block,
      ]),
      headStyles: { fillColor: [7, 26, 51], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 8, textColor: [7, 26, 51] },
      alternateRowStyles: { fillColor: [248, 246, 240] },
    });
  }

  addFooter(pdf, generatedBy);
  pdf.save(`Faculty_Details_${data.facultyId}.pdf`);
}

export interface FeedbackClassReportData {
  department: string;
  departmentCode: string;
  year: number;
  section: string;
  academicYear: string;
  rows: FeedbackClassReportRow[];
}

export async function generateFeedbackClassReportPdf(data: FeedbackClassReportData, generatedBy: string) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const startY = await addHeader(pdf, "Faculty Feedback Report", data.academicYear);

  const y = fieldRows(pdf, startY + 10, [
    ["Department", `${data.department} (${data.departmentCode})`],
    ["Year / Section", `Year ${data.year} - ${data.section}`],
    ["Academic Year", data.academicYear],
    ["Date", new Date().toLocaleDateString("en-IN", { dateStyle: "medium" })],
  ]);

  if (data.rows.length === 0) {
    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(10);
    pdf.setTextColor(SLATE);
    pdf.text("No feedback has been submitted for this class yet.", MARGIN, y + 20);
  } else {
    autoTable(pdf, {
      startY: y + 10,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Subject", "Faculty Name", "Percentage"]],
      body: data.rows.map((r) => [r.subjectName, r.facultyName, r.percentage === null ? "—" : `${r.percentage.toFixed(2)}%`]),
      headStyles: { fillColor: [7, 26, 51], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, textColor: [7, 26, 51] },
      alternateRowStyles: { fillColor: [248, 246, 240] },
    });
  }

  addFooter(pdf, generatedBy);
  pdf.save(`Faculty_Feedback_Report_${data.departmentCode}_Y${data.year}${data.section}.pdf`);
}

export async function generateFacultyFeedbackReportPdf(data: FeedbackFacultyDetail, generatedBy: string) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const startY = await addHeader(
    pdf,
    `Feedback Analysis Report : ${data.departmentCode}-${data.section} ${data.year} Sem`,
    data.academicYear
  );

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(NAVY);
  pdf.text(`${data.subjectName} - ${data.facultyName}`, pdf.internal.pageSize.getWidth() / 2, startY + 6, { align: "center" });

  autoTable(pdf, {
    startY: startY + 24,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Questionnaire", "5", "4", "3", "2", "1"]],
    body: data.questions.map((q) => [q.text, q.counts[5], q.counts[4], q.counts[3], q.counts[2], q.counts[1]]),
    headStyles: { fillColor: [7, 26, 51], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9, textColor: [7, 26, 51] },
    columnStyles: {
      1: { halign: "center" },
      2: { halign: "center" },
      3: { halign: "center" },
      4: { halign: "center" },
      5: { halign: "center" },
    },
    alternateRowStyles: { fillColor: [248, 246, 240] },
  });

  const finalY = (pdf as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.setTextColor(GOLD);
  pdf.text(`FEEDBACK % : ${data.percentage.toFixed(2)}%`, pdf.internal.pageSize.getWidth() / 2, finalY + 30, { align: "center" });

  if (data.comments.length > 0) {
    const pageWidth = pdf.internal.pageSize.getWidth();
    let y = finalY + 58;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(NAVY);
    pdf.text("STUDENT SUGGESTIONS / FEEDBACK", MARGIN, y);
    y += 16;

    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(9);
    pdf.setTextColor(SLATE);
    for (const comment of data.comments) {
      const lines = pdf.splitTextToSize(`“${comment}”`, pageWidth - MARGIN * 2);
      if (y + lines.length * 12 > pdf.internal.pageSize.getHeight() - 70) {
        pdf.addPage();
        y = MARGIN;
      }
      pdf.text(lines, MARGIN, y);
      y += lines.length * 12 + 8;
    }
  }

  addFooter(pdf, generatedBy);
  pdf.save(`Feedback_${data.facultyId}_${data.subjectCode}.pdf`);
}
